refactor: use workspace as workspace directory.

diff --git a/dotfilerc b/dotfilerc
--- a/dotfilerc
+++ b/dotfilerc
@@ -2,18 +2,18 @@
 export DOTFILES_DIR="$(dirname $0)"
 SCRIPTS="${DOTFILES_DIR}/scripts"
 
-command_exists () {
-    type "$1" &> /dev/null ;
+command_exists() {
+	type "$1" &>/dev/null
 }
 
 if command_exists dotfiles; then
-    echo "dotfiles already initialized"
-    return 0
+	echo "dotfiles already initialized"
+	return 0
 fi
 
 for script in ${SCRIPTS}/*.sh; do
-    if ! source $script; then
-        echo "Failed to source $script"
-        exit 1
-    fi
+	if ! source $script; then
+		echo "Failed to source $script"
+		exit 1
+	fi
 done
